on: 
  push:
    branches:
      - main
jobs:
  setup-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/github-demo
            rm -rf *

      - name: deploy
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.PORT }}
          localPath: './env/'
          remotePath: '/home/github-demo/'