on: 
  push:
    branches:
      - main
jobs:
  setup-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.PORT }}
          localPath: './package.json'
          remotePath: '/home/github-demo'